Repository decide-single-chullo/decide, pull requests merged in 2022-01, with the labels that each got.

#35 fix: Arreglo en test de voting
  decide/store/migrations/0001_initial.py
  decide/voting/migrations/0001_initial.py
  decide/voting/tests.py
Labels: bug, high priority

#38 Fix/edicion voting
  decide/voting/models.py
  decide/voting/tests.py
Labels: bug, high priority

#40 fix: Arreglo configuración selenium
  requirements.txt
Labels: bug, configuration, high priority

#42 fix: Problema configuración Github Actions
  .github/workflows/django.yml
Labels: bug, configuration, high priority

#45 feature: Implementar enviar un email cuando se haga un recuento con el resultado
  decide/decide/settings.py
  decide/voting/admin.py
  decide/voting/models.py
  decide/voting/templates/count.html
  requirements.txt
Labels: feature, medium priority

#46 fix: impedida la edición/borrado de preguntas en votings empezadas
  decide/base/tests.py
  decide/census/tests.py
  decide/voting/admin.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: bug, high priority

#50 Incidencia: No permitir subir archivos que no sean csv al cargar censos desde csv
  decide/census/views.py
Labels: bug, high priority

#55 fix: fixeado settings.py
  decide/decide/settings.py
Labels: bug, configuration, high priority

#57 fix: arreglo import settings.py
  decide/decide/settings.py
Labels: bug, configuration, high priority

#44 feature: Implementar mostrar información relevante en tiempo real
  decide/visualizer/templates/visualizer/visualizer.html
  decide/voting/admin.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/tests.py
Labels: feature, medium priority

#62 Incidencia: Corregir número de votos correcto al hacer el recuento bug high priority
  decide/voting/models.py
  decide/voting/templates/count.html
Labels: bug, high priority

#64 feature: Implementar autenticacion por email en el sistema
  decide/authentication/backends.py
  decide/authentication/tests.py
  decide/decide/settings.py
Labels: feature, medium priority

#52 feature: Implementdos tests de census para la carga de censos desde csv
  decide/census/csvs/test.txt
  decide/census/csvs/test_empty.csv
  decide/census/csvs/test_full.csv
  decide/census/csvs/test_no_sense.csv
  decide/census/templates/census/upload.html
  decide/census/tests.py
  decide/census/views.py
  decide/voting/tests.py
Labels: feature, medium priority

#65 feature: Implementación de mensaje emergente con recuento de la votación
  decide/voting/admin.py
  decide/voting/tests.py
Labels: feature, medium priority

#70 Incidencia: arreglar conflicto en algunos test de voting
  decide/base/tests.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: bug, high priority

#72 fix: arreglada incidencia con atributo number de question
  decide/census/tests.py
  decide/voting/admin.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: bug, high priority

#74 Incidencia: fallos en test selenium Census
  decide/census/tests.py
Labels: bug, high priority

#75 feature: Implementar test de Selenium
  decide/authentication/tests.py
  decide/base/tests.py
  decide/store/views.py
  decide/voting/tests.py
Labels: feature, medium priority

#76 feature: Implementar tests de Selenium
  decide/voting/tests.py
Labels: feature, medium priority

#81 Incidencia: Arreglar conflicto de test de store y añadir nuevos.
  decide/postproc/tests.py
  decide/store/tests.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: bug, high priority

#82 feature: Implementar tests de Selenium
  decide/voting/tests.py
Labels: feature, medium priority

#83 feature: Implementar tests
  decide/voting/tests.py
Labels: feature, medium priority

#84 fix: Eliminado test_mensaje_tally()
  decide/voting/tests.py
Labels: bug, high priority

#78 feature: Implementar test de carga del sistema
  loadtest/locustfile.py
  requirements.txt
Labels: feature, medium priority

#86 Implementar test de Selenium de visualizer
  decide/visualizer/tests.py
Labels: feature, medium priority

#87 fix: Arreglos generales de tests
  decide/census/tests.py
  decide/decide/settings.py
  decide/voting/models.py
  decide/voting/tests.py
Labels: bug, configuration, high priority

#88 Actualización del código de la rama develop-workflows con el contenido de develop.
  .vscode/launch.json
  decide/authentication/backends.py
  decide/authentication/tests.py
  decide/base/tests.py
  decide/booth/templates/booth/booth.html
  decide/booth/urls.py
  decide/booth/views.py
  decide/census/csvs/test.txt
  decide/census/csvs/test_empty.csv
  decide/census/csvs/test_full.csv
  decide/census/csvs/test_no_sense.csv
  decide/census/migrations/0002_auto_20211219_1643.py
  decide/census/templates/census/upload.html
  decide/census/tests.py
  decide/census/views.py
  decide/decide/settings.py
  decide/postproc/tests.py
  decide/store/migrations/0001_initial.py
  decide/store/models.py
  decide/store/serializers.py
  decide/store/tests.py
  decide/store/views.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/voting/admin.py
  decide/voting/migrations/0001_initial.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/templates/count.html
  decide/voting/tests.py
  loadtest/locustfile.py
  requirements.txt
Labels: configuration, deployment, medium priority

#89 Actualización del código de la rama develop-docker con el contenido de develop
  .vscode/launch.json
  decide/authentication/backends.py
  decide/authentication/tests.py
  decide/base/tests.py
  decide/booth/templates/booth/booth.html
  decide/booth/urls.py
  decide/booth/views.py
  decide/census/csvs/test.txt
  decide/census/csvs/test_empty.csv
  decide/census/csvs/test_full.csv
  decide/census/csvs/test_no_sense.csv
  decide/census/migrations/0002_auto_20211219_1643.py
  decide/census/templates/census/upload.html
  decide/census/tests.py
  decide/census/views.py
  decide/decide/settings.py
  decide/postproc/tests.py
  decide/store/migrations/0001_initial.py
  decide/store/models.py
  decide/store/serializers.py
  decide/store/tests.py
  decide/store/views.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/voting/admin.py
  decide/voting/migrations/0001_initial.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/templates/count.html
  decide/voting/tests.py
  loadtest/locustfile.py
  requirements.txt
Labels: configuration, deployment, medium priority

#92 Unión de develop (versión de pre lanzamiento) con develop-heroku
  decide/authentication/backends.py
  decide/authentication/tests.py
  decide/base/tests.py
  decide/booth/templates/booth/booth.html
  decide/booth/urls.py
  decide/booth/views.py
  decide/census/admin.py
  decide/census/csvs/test.txt
  decide/census/csvs/test_empty.csv
  decide/census/csvs/test_full.csv
  decide/census/csvs/test_no_sense.csv
  decide/census/forms.py
  decide/census/models.py
  decide/census/templates/census/upload.html
  decide/census/tests.py
  decide/census/urls.py
  decide/census/views.py
  decide/decide/settings.py
  decide/local_settings.example.py
  decide/postproc/tests.py
  decide/store/migrations/0001_initial.py
  decide/store/models.py
  decide/store/serializers.py
  decide/store/tests.py
  decide/store/views.py
  decide/visualizer/templates/visualizer/visualizer.html
  decide/visualizer/tests.py
  decide/voting/admin.py
  decide/voting/migrations/0001_initial.py
  decide/voting/models.py
  decide/voting/serializers.py
  decide/voting/templates/count.html
  decide/voting/tests.py
  decide/voting/views.py
  loadtest/locustfile.py
  requirements.txt
Labels: configuration, deployment, medium priority

#96 fix: versión 1.0.0 error
  decide/decide/settings.py
Labels: bug, configuration, high priority

#97 Hotfix/1.0.0
  decide/decide/settings.py
Labels: bug, configuration, high priority
